[package]
name = "cherry-harvest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.16.1"
temp-dir = "0.1.11"
env_logger = "0.10.0"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.14"
derivative = "2.2.0"
ngrammatic = "0.4.0"
hora = "0.1.1"
firestorm = { version= "0.5.1", features=["enable_system_time"] }

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "ann_search"
harness = false
